In [1]:
import numpy as np
from numpy import genfromtxt


In [7]:
data = genfromtxt(r"D:/STUDY/OPENCV/drive-download-20240131T012424Z-001/Computer-Vision-with-Python/Computer-Vision-with-Python/DATA/bank_note_data.txt", delimiter = ",")

In [8]:
data


array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [10]:
features = data[:,0:4]


In [11]:
X= features
X

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [18]:
y = labels = data[:,4]

In [19]:
y

array([0., 0., 0., ..., 1., 1., 1.])

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [22]:
X

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [23]:
len(X_train)

919

In [24]:
from sklearn.preprocessing import MinMaxScaler

In [27]:
scaler_object = MinMaxScaler()

In [30]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [32]:
scaled_x_train = scaler_object.transform(X_train) 

In [33]:
scaled_x_train

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [35]:
from keras.models import Sequential
from keras.layers import Dense

In [37]:
model = Sequential()
model.add(Dense(4, input_dim= 4, activation = "relu"))
model.add(Dense(8, activation = "relu"))
model.add(Dense(1, activation = "sigmoid"))

In [39]:
model.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

In [41]:
model.fit(scaled_x_train, y_train, epochs= 50, verbose = 2)

Epoch 1/50
 - 0s - loss: 0.7270 - acc: 0.4026
Epoch 2/50
 - 0s - loss: 0.7010 - acc: 0.5180
Epoch 3/50
 - 0s - loss: 0.6876 - acc: 0.5604
Epoch 4/50
 - 0s - loss: 0.6783 - acc: 0.5756
Epoch 5/50
 - 0s - loss: 0.6696 - acc: 0.6017
Epoch 6/50
 - 0s - loss: 0.6590 - acc: 0.6279
Epoch 7/50
 - 0s - loss: 0.6445 - acc: 0.6659
Epoch 8/50
 - 0s - loss: 0.6316 - acc: 0.6659
Epoch 9/50
 - 0s - loss: 0.6210 - acc: 0.6725
Epoch 10/50
 - 0s - loss: 0.6115 - acc: 0.6561
Epoch 11/50
 - 0s - loss: 0.6022 - acc: 0.6616
Epoch 12/50
 - 0s - loss: 0.5933 - acc: 0.6746
Epoch 13/50
 - 0s - loss: 0.5842 - acc: 0.6757
Epoch 14/50
 - 0s - loss: 0.5741 - acc: 0.6899
Epoch 15/50
 - 0s - loss: 0.5645 - acc: 0.7008
Epoch 16/50
 - 0s - loss: 0.5544 - acc: 0.7225
Epoch 17/50
 - 0s - loss: 0.5446 - acc: 0.7323
Epoch 18/50
 - 0s - loss: 0.5357 - acc: 0.7334
Epoch 19/50
 - 0s - loss: 0.5245 - acc: 0.7378
Epoch 20/50
 - 0s - loss: 0.5158 - acc: 0.7486
Epoch 21/50
 - 0s - loss: 0.5036 - acc: 0.7476
Epoch 22/50
 - 0s - lo

In [44]:
scaler_object.fit(X_test)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [45]:
scaled_x_test = scaler_object.transform(X_test)

In [46]:
scaled_x_test

array([[0.65576832, 0.76019778, 0.22784929, 0.52919178],
       [0.51021119, 0.83150383, 0.09609469, 0.51778828],
       [0.53621584, 0.78751834, 0.14430053, 0.45740888],
       ...,
       [0.80892829, 0.62703326, 0.28324337, 0.80218187],
       [0.96584712, 0.91587388, 0.03898168, 0.37308892],
       [0.51587076, 0.87148571, 0.07061886, 0.10285426]])

In [47]:
model.predict_classes(scaled_x_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    

In [48]:
model. metrics_names

['loss', 'acc']

In [49]:
model.evaluate(x=scaled_x_test, y = y_test)

453/453 [==============================] - 0s 108us/step


[0.19437120000422659, 0.9381898454746137]

In [50]:
from sklearn.metrics import confusion_matrix, classification_report

In [51]:
predictions = model.predict_classes(scaled_x_test)

In [52]:
confusion_matrix(y_test, predictions)

array([[256,   1],
       [ 27, 169]], dtype=int64)

In [53]:
model.save("myfirstmodel.h5")

In [55]:
from keras.models import load_model

In [56]:
new_model = load_model("myfirstmodel.h5")

In [58]:
new_model.predict_classes(X_test)

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    